# Generated by Django 4.2.2 on 2023-08-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HelloWorld",
        ),
    ]
